# -Denv=dev -Dapollo.cluster=DEFAULT -Dserver.port=53050
app:
  id: consumer-service
apollo:
  bootstrap:
    enabled: true
    namespaces: application,micro_service.spring-boot-druid,micro_service.spring-boot-http,micro_service.spring-eureka,micro_service.spring-hystrix,micro_service.spring-ribbon,micro_service.spring-boot-redis,micro_service.mybatis-plus,micro_service.spring-rocketmq,micro_service.spring-cloud-hmily

server:
  port: 53050

spring:
  application:
    name: consumer-service

logging:
  config: classpath:log4j2-dev.xml

#
#ureka:
# server:
#   enable-self-preservation: false    #关闭服务器自我保护，客户端心跳检测15分钟内错误达到80%服务会保护，导致别人还认为是好用的服务
#   eviction-interval-timer-in-ms: 10000 #清理间隔（单位毫秒，默认是60*1000）5秒将客户端剔除的服务在服务注册列表中剔除#
#   shouldUseReadOnlyResponseCache: true #eureka是CAP理论种基于AP策略，为了保证强一致性关闭此切换CP 默认不关闭 false关闭
# client:
#   register-with-eureka: false  #false:不作为一个客户端注册到注册中心
#   fetch-registry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server
#   serviceUrl:
#     defaultZone: http://localhost:53000/eureka/
# instance:
#   hostname: ${spring.cloud.client.ip-address}
#   prefer-ip-address: true  #注册时使用IP地址，而不是服务名